# Generated by Django 4.2.3 on 2023-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_alter_custom_user_profile_custom_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='custom_user1',
            name='prof',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile',
            field=models.ManyToManyField(to='FirstApp.profile'),
        ),
        migrations.AddField(
            model_name='custom_user1',
            name='prof',
            field=models.ManyToManyField(to='FirstApp.profile'),
        ),
    ]
