# Generated by Django 4.2.3 on 2023-08-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_remove_custom_user_profile_remove_custom_user1_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user1',
            name='prof',
        ),
        migrations.DeleteModel(
            name='Custom_User',
        ),
        migrations.DeleteModel(
            name='Custom_User1',
        ),
    ]
